apiVersion: v1
kind: ReplicationController
metadata:
  name: geobin
  labels:
    provider: geobin
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: geobin
    spec:
      containers:
      - name: geobin
        image: nullstyle/geobin
        ports:
        - containerPort: 5432
