name: geobin
home: http://github.com/nullstyle/geobin
version: 0.1.0
description: A repository of simple geographic features
maintainers:
- Scott Fleckenstein <nullstyle@gmail.com>
details: |-
  TODO
